### ISSUE TITLE
Remove the tabindex?

### ISSUE THREAD

**Issue by blowback** [eye-wave/web-knobs#1]
Thanks for the library - looks great! Any chance of an option to remove the `tabindex=0` - it causes an ugly rectangular outline of the control when it is focused.

**Comment by eye-wave** [comment]
I could make a style for :focus state that isn't as flashy as the default

**Comment by eye-wave** [comment]
should be all fixed up now!

**Comment by blowback** [comment]
Perfect, thanks!
